            <div id="footer">
                <hr noshade size="1">
                <div id="textlinks">
                    <p><a href="index.php">Home</a>  |  <a href="about.php">About Us</a>  |  <a href="pubs.php">Publications</a>  |  <a href="research.php">Research</a>  |  <a href="contact.php">Contact Us</a></p>
                </div>
                <div id="nsf">
                    <div>
						<img style="position:relative; margin-right:10px; width:75px;" src="images/logos/NSF_logo.png" alt="National Science Foundation" title="National Science Foundation" />
					</div>
					<p style="position:absolute; padding: 0 0px 0 75px;">
						The K&ndash;12 Mathematics Curriculum Center was funded by the <a href="http://www.nsf.gov" target="_blank">National Science Foundation</a> to inform and assist schools and districts as they select and implement Standards-based mathematics curricula.
					</p>
                </div>
                <div id="edc">
                    <p>
						<a href="http://main.edc.org" target="_blank">
							<img style="width:150px" src="images/logos/edc_logo.jpg" alt="Education Development Center, Inc." title="Education Development Center, Inc." /><br />
							Copyright &copy; 2016 by Education Development Center, Inc.
						</a>
					</p>
                </div>
            </div>
