            <div id="footer">
                <hr noshade size="1">
                <div id="textlinks">
                    <p><a href="index.php">Home</a>  |  <a href="about.php">About Us</a>  |  <a href="pubs.php">Publications</a>  |  <a href="research.php">Research</a>  |  <a href="contact.php">Contact Us</a></p>
                </div>
                <div id="nsf">
                    <p>The K&ndash;12 Mathematics Curriculum Center is funded by the <a href="http://www.nsf.gov">National Science Foundation</a> to inform and assist schools and districts as they select and implement Standards-based mathematics curricula.</p>
                </div>
                <div id="edc">
                    <p>Site hosted by<br />
                    <a href="http://main.edc.org">Education Development Center, Inc.</a> <br />
                    <a href="http://main.edc.org/info/legal.asp">&copy; 2016  All rights reserved.</a></p>
                </div>
            </div>
