            <div id="navigation">
                <ul>
                    <li><a href="about.php">About Us</a></li>
                    <li><a href="pubs.php">Publications</a></li>
                    <li><a href="research.php">Research</a></li>
                    <!--<li><a href="resources.php">Other Resources </a></li>-->
                    <li><a href="contact.php">Contact Us</a></li>
                </ul>
                <!--<div id="search">
                    <form name="look" method="GET" action="http://google2.edc.org/search">
                        <input name="q" type="text" value="Search K-12" size="20">
                        <br/><br/>
                        <input type="submit" value="Search Site" name="btng">
                        <input type="hidden" name="site" value="mcc">
                        <input type="hidden" name="output" value="xml_no_dtd">
                        <input type="hidden" name="client" value="edc_general">
                        <input type="hidden" name="proxystylesheet" value="edc_general">
                    </form>
                </div>-->
            </div>
